kis:
  app:
    key: ${KIS_APP_KEY}
    secret: ${KIS_APP_SECRET}
  domain:
    real: ${REAL_BASE_URL}
    virtual: ${VIRTUAL_BASE_URL}

# ?? ??
server:
  port: 8080
#  ssl:
#    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: mappings

#MySQL ??
spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/stock?serverTimezone=Asia/Seoul
    username: ${MYSQL_NAME}
#    username: root
    password: ${MYSQL_PASSWORD}
#    password: 1234


#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        open-in-view: false

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true

  # Redis ??
  data:
    redis:
      sentinel:
        master:
          host: ${REDIS_HOST:localhost}
          port: 6379
        nodes:
          - ${REDIS_PORT1:localhost}:26379
          - ${REDIS_PORT2:localhost}:26380
          - ${REDIS_PORT3:localhost}:26381
      timeout: 10000

  flyway:
    enabled: true  # flway ??(??? true)
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul  # DB ??
    username: ${MYSQL_NAME}  # DB user ???
    password: ${MYSQL_PASSWORD}  # DB user ???
    baseline-on-migrate: true  # Baseline ??(???? ???? ?????? ?? ??? ??)
    locations: classpath:db/migration/{vendor}  #?????? ?? ?? ??(?? ??: db/migration )