name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/stock-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/stock-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. 프로젝트 폴더로 위치 이동
            cd /home/ubuntu/stock 
            
            # 2. 최신 코드 레포지토리 가져오기
            git pull origin main
            
            # 3. 배포 환경용 .env.prod 파일 생성 (GitHub Secrets에서 가져옴)
            echo "${{ secrets.ENV_PROD }}" > .env.prod
            
            # 4. 최신 도커 이미지 Pull
            docker-compose --env-file .env.prod -f docker-compose.prod.yml pull
            
            # 5. 기존 서비스 중지 및 재시작 (새 이미지 반영)
            docker-compose --env-file .env.prod -f docker-compose.prod.yml down
            docker-compose --env-file .env.prod -f docker-compose.prod.yml up -d
            
            # 6. 사용하지 않는 불필요한 도커 이미지들 정리 (디스크 공간 확보용)
            docker image prune -af
